#! /bin/zsh
#
# ~/.zshrc 
# ==============================================================================
#
# This .zshrc is  highly vim-oriented and myself-oriented,  so if you don't use
# vim and if you aren't me, you must edit this file
#


# If not running interactively, don't do anything
[[ $- != *i* ]] && return

eval `dircolors ~/.dir_colors`


# Antigen plugins management
# ==============================================================================

. ~/.antigen.zsh

antigen bundle zsh-users/zsh-syntax-highlighting	# Syntax highlighting
antigen bundle Seninha/Epic-zsh-plugins aliases		# Epic aliases
antigen bundle Seninha/Epic-zsh-plugins completion	# Epic completion
antigen bundle Seninha/Epic-zsh-plugins history		# Epic history
antigen bundle Seninha/Epic-zsh-plugins modules		# Epic modules
antigen bundle Seninha/Epic-zsh-plugins options		# Epic options
antigen bundle Seninha/Epic-zsh-plugins vimBindkeys	# Epic bindkeys

antigen theme Seninha/Epic-zsh-theme epic		# An AWESOME theme


antigen apply


# Basic Configuration
# ==============================================================================

cmd () {
	wine ~/.local/share/PyCmd/PyCmd.exe
	reset
}

alias volume=alsamixer
alias desligar=poweroff
alias reiniciar=reboot
alias tetris=vitetris
alias enpt='zztradutor en-pt '
alias pten='zztradutor pt-en '


# PATHs
path=(~/bin ~/.local/bin)	# Personal bin dir
path+=(/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games)
path+=/opt/java/bin		# Java bin dir
path+=./				# You can execute a command in current dir without prefixing "./"
path+="`ruby -e 'puts Gem.user_dir'`/bin"
QT_PLUGIN_PATH=/usr/lib32/kde4/plugins/:/home/lucas/.kde4/lib/kde4/plugins/:/usr/lib/kde4/plugins/

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:~/bin:~/.local/lib"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/java/jre/lib/i386/"

fpath=(/usr/share/zsh/site-functions $fpath)

# Paging and Editing
export PAGER="vimpager"
export EDITOR="/usr/bin/vim"
export VISUAL="/usr/bin/vim"
NULLCMD=vimcat
READNULLCMD=$PAGER

# DEV
export WINEDEBUG='fixme-all'
export GCC_COLORS

# Personal Variables
export WWW_HOME="http://seninha.net"

function :t () {
if [[ -n $* ]]; then
    project=$(basename `pwd`);
    tp=( $(\task _projects | grep $project) );

    if [[ -n $tp ]]; then
        \task "$@" project:$project
    else
        \task "$@"
    fi
else
    \task
fi
}

alias task=':t'
alias week='task +WEEK next'
alias month='task +MONTH next'
alias calendar='task calendar && task +MONTH next'
alias cal='task calendar && task +MONTH next'


# Programs Run at Login Time
# ==============================================================================
#
# ¡The following commands may require a package to be installed!
# ¡The following commands may be meaningless in a computer other than mine!
#

## Start tmux (requires tmux)
# if which tmux 2>&1 >/dev/null; then
#         # if no session is started, start a new session
#         test -z ${TMUX} && tmux && exit
#         
#         # when quitting tmux, try to attach
#         while test -z ${TMUX}; do
#                 tmux attach || break
#         done
# fi

# Show a random awesome frase
fortune 90% brasil 5% linux 5% linuxcookie | cowsay -f tux

# Instalacao das Funcoes ZZ (www.funcoeszz.net)
export ZZPATH=/usr/bin/funcoeszz
source /home/lucas/.zzzshrc
